name: talktoyourdocument_app
description: AI-powered document analysis mobile application for TalkToYourDocument API v2.0
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase & Authentication
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6

  # HTTP & API
  dio: ^5.3.4
  json_annotation: ^4.8.1
  retrofit: ^4.0.3

  # File handling
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  permission_handler: ^11.1.0

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # UI & Navigation
  go_router: ^12.1.3
  flutter_markdown: ^0.6.18
  cached_network_image: ^3.3.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^2.7.0

  # Charts & Visualization
  fl_chart: ^0.65.0
  charts_flutter: ^0.12.0

  # Utilities
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  uuid: ^4.2.1
  logger: ^2.0.2+1

  # Icons & Fonts
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

  # Platform specific
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  riverpod_generator: ^2.3.9

  # Linting
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/

  # Fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

# Flutter configuration
flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated

# Build configuration
targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake_case
          include_if_null: false
